// Shared helpers for TDIA Intelligence Engine edge functions.
// Source of truth: https://github.com/LuckyyKid/tdia-intelligence-engine
// DO NOT modify formulas here — mirror the upstream repo exactly.

export const ENGINE_VERSION_TAG = "Generated by TDIA Intelligence Engine v1.0";

export const corsHeaders = {
  "content-type": "application/json",
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "POST, OPTIONS",
  "access-control-allow-headers":
    "authorization, x-client-info, apikey, content-type, x-tdia-user",
};

export function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: corsHeaders });
}

export function clamp(v: number, min: number, max: number): number {
  return Math.min(Math.max(v, min), max);
}
export function roundTo(v: number, decimals = 4): number {
  const f = 10 ** decimals;
  return Math.round((v + Number.EPSILON) * f) / f;
}
export function pctInc(base: number, lift: number): number {
  return roundTo(base * (1 + lift / 100));
}
export function pctDec(base: number, lift: number): number {
  return roundTo(base * (1 - lift / 100));
}

export class ModelValidationError extends Error {
  issues: { path: string; message: string }[];
  constructor(issues: { path: string; message: string }[]) {
    super("Model input validation failed.");
    this.name = "ModelValidationError";
    this.issues = issues;
  }
}

export function toErrorPayload(e: unknown) {
  if (e instanceof ModelValidationError) return { error: e.message, issues: e.issues };
  return { error: e instanceof Error ? e.message : "Unknown error." };
}
export function errorStatus(e: unknown): number {
  if (e instanceof ModelValidationError || e instanceof SyntaxError) return 400;
  return 500;
}

export type ModelRunRecord = {
  client_id: string | null;
  model_name: string;
  model_version: string;
  input_json: unknown;
  output_json: unknown;
  formula_used: unknown;
  generated_by?: string | null;
};

export async function insertModelRun(record: ModelRunRecord) {
  const url = Deno.env.get("SUPABASE_URL");
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !key) return { inserted: false, skipped: true, reason: "missing_supabase_env" as const };

  const res = await fetch(`${url.replace(/\/$/, "")}/rest/v1/model_runs`, {
    method: "POST",
    headers: {
      apikey: key,
      authorization: `Bearer ${key}`,
      "content-type": "application/json",
      prefer: "return=representation",
    },
    body: JSON.stringify(record),
  });
  if (!res.ok) {
    return { inserted: false, skipped: false, reason: "insert_failed" as const, status: res.status, error: await res.text() };
  }
  const rows = await res.json();
  return { inserted: true as const, skipped: false, row: Array.isArray(rows) ? rows[0] : rows };
}
