import { Badge } from "@/components/ui/badge";
import { Sparkles } from "lucide-react";

export function ModelBadge({ version = "v1.0" }: { version?: string }) {
  return (
    <Badge variant="secondary" className="gap-1 font-normal">
      <Sparkles className="h-3 w-3" />
      Generated by TDIA Intelligence Engine {version}
    </Badge>
  );
}

export function ForecastDisclaimer() {
  return (
    <p className="text-xs italic text-muted-foreground">
      This is a conditional forecast, not a guarantee.
    </p>
  );
}
