
ALTER TABLE public.gos_spending_power_snapshots
  ADD COLUMN IF NOT EXISTS model_type TEXT DEFAULT 'V1_THRESHOLD',
  ADD COLUMN IF NOT EXISTS sample_size INT,
  ADD COLUMN IF NOT EXISTS regression_slope_cac NUMERIC,
  ADD COLUMN IF NOT EXISTS regression_intercept_cac NUMERIC,
  ADD COLUMN IF NOT EXISTS r_squared_cac NUMERIC,
  ADD COLUMN IF NOT EXISTS regression_slope_mer NUMERIC,
  ADD COLUMN IF NOT EXISTS regression_intercept_mer NUMERIC,
  ADD COLUMN IF NOT EXISTS r_squared_mer NUMERIC,
  ADD COLUMN IF NOT EXISTS backtest_error_percent NUMERIC,
  ADD COLUMN IF NOT EXISTS recommended_model_confidence INT,
  ADD COLUMN IF NOT EXISTS fallback_reason TEXT,
  ADD COLUMN IF NOT EXISTS planned_spend NUMERIC,
  ADD COLUMN IF NOT EXISTS projected_cac_low NUMERIC,
  ADD COLUMN IF NOT EXISTS projected_cac_base NUMERIC,
  ADD COLUMN IF NOT EXISTS projected_cac_high NUMERIC,
  ADD COLUMN IF NOT EXISTS projected_mer_low NUMERIC,
  ADD COLUMN IF NOT EXISTS projected_mer_base NUMERIC,
  ADD COLUMN IF NOT EXISTS projected_mer_high NUMERIC,
  ADD COLUMN IF NOT EXISTS recommended_spend_low NUMERIC,
  ADD COLUMN IF NOT EXISTS recommended_spend_base NUMERIC,
  ADD COLUMN IF NOT EXISTS recommended_spend_high NUMERIC,
  ADD COLUMN IF NOT EXISTS spend_risk TEXT,
  ADD COLUMN IF NOT EXISTS efficiency_risk TEXT,
  ADD COLUMN IF NOT EXISTS risks JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS conditions JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS spending_history JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS summary TEXT;
